#!/bin/bash

echo "🚀 Alfred the Butler - Render Deployment Helper"
echo "================================================"

echo ""
echo "📋 Pre-Deployment Checklist:"
echo "1. ✅ SignalWire configured"
echo "2. ✅ Webhook URL set"
echo "3. ✅ Environment variables ready"
echo "4. ✅ GitHub repository connected"

echo ""
echo "🌐 Render Setup Steps:"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your repository: personal_sms_assistant"
echo "5. Configure:"
echo "   - Name: alfred-the-butler"
echo "   - Environment: Python 3"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: cd src && python app.py"
echo "   - Plan: Free"

echo ""
echo "🔧 Environment Variables to Add:"
echo "GOOGLE_CLIENT_ID=your_google_client_id"
echo "GOOGLE_CLIENT_SECRET=your_google_client_secret"
echo "GMAIL_WEBHOOK_SECRET=your_gmail_webhook_secret"
echo "SIGNALWIRE_PROJECT_ID=your_project_id"
echo "SIGNALWIRE_AUTH_TOKEN=your_auth_token"
echo "SIGNALWIRE_SPACE_URL=https://the-butler.signalwire.com"
echo "SIGNALWIRE_PHONE_NUMBER=+13092885370"
echo "COMMUNICATION_MODE=hybrid"
echo "PUSHOVER_EMAIL_ALIAS=your_pushover_email"
echo "MORNING_CHECKIN_HOUR=8"
echo "GMAIL_POLLING_INTERVAL=5"

echo ""
echo "📱 After Deployment:"
echo "1. Update SignalWire webhook to your Render URL"
echo "2. Test with: curl https://your-app.onrender.com/health"
echo "3. Send SMS to +13092885370"
echo "4. Check logs in Render dashboard"

echo ""
echo "🎯 Your app will be at: https://alfred-the-butler.onrender.com"
echo "================================================"
